### ISSUE TITLE
Move non-database model relative classes outside of `/models` folder

### ISSUE THREAD

**Issue by dimmon908** [LyubovP/DoctorApp#21]
https://github.com/LyubovP/DoctorApp/blob/f911d538e1f11c579d3c8cec6dd8ea70b6578094/app/models/ability.rb#L1

We could separate ruby classes to database-related(models), some sort of  presenters(represent data in some way), services(how to save data in db), some business logic or some another way

**Comment by LyubovP** [comment]
I moved the ability.rb file to the app/abilities folder
